create table if not exists users (
  id bigint generated by default as identity primary key,
  username varchar(50) not null unique,
  password_hash varchar(100) not null,
  email varchar(200),
  enabled boolean not null,
  role varchar(20) not null
);

create table if not exists stays (
  id bigint generated by default as identity primary key,
  user_key varchar(100) not null,
  entry_date date not null,
  exit_date date not null
);

create index if not exists idx_stays_user_entry on stays(user_key, entry_date);
create index if not exists idx_stays_user_exit on stays(user_key, exit_date);

create table if not exists persistent_logins (
  username varchar(64) not null,
  series varchar(64) primary key,
  token varchar(64) not null,
  last_used timestamp not null
);

create table if not exists password_reset_tokens (
  id bigint generated by default as identity primary key,
  username varchar(50) not null,
  token_hash varchar(128) not null,
  expires_at timestamp not null,
  used boolean not null
);

create index if not exists idx_prt_user on password_reset_tokens(username);
create index if not exists idx_prt_expires on password_reset_tokens(expires_at);
